version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    volumes:
      - .:/code
    links:
      - db:db
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    hostname: db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports: 
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/

volumes:
  data: